org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
android.useAndroidX=true
kotlin.code.style=official
kotlin.incremental=false
kotlin.caching.enabled=false
kotlin.daemon.jvmargs=-Xmx1500m
android.disableAutomaticComponentClear=true
android.overrideAarMetadataCheck=true

# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
